config/routes.rb
Rails.application.routes.draw do
  resources :strikes

end

app/models/strike.rb
class Strike < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/strikes_controller.rb
class StrikesController < ApplicationController
  before_action :set_strike, only: [:show, :edit, :update, :destroy]

  # GET /strikes
  # GET /strikes.json
  def index
    @strikes = Strike.all
  end

  # GET /strikes/1
  # GET /strikes/1.json
  def show
  end

  # GET /strikes/new
  def new
    @strike = Strike.new
  end

  # GET /strikes/1/edit
  def edit
  end

  # POST /strikes
  # POST /strikes.json
  def create
    @strike = Strike.new(strike_params)

    respond_to do |format|
      if @strike.save
        format.html { redirect_to @strike, notice: 'Strike was successfully created.' }
        format.json { render :show, status: :created, location: @strike }
      else
        format.html { render :new }
        format.json { render json: @strike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strikes/1
  # PATCH/PUT /strikes/1.json
  def update
    respond_to do |format|
      if @strike.update(strike_params)
        format.html { redirect_to @strike, notice: 'Strike was successfully updated.' }
        format.json { render :show, status: :ok, location: @strike }
      else
        format.html { render :edit }
        format.json { render json: @strike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strikes/1
  # DELETE /strikes/1.json
  def destroy
    @strike.destroy
    respond_to do |format|
      format.html { redirect_to strikes_url, notice: 'Strike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strike
      @strike = Strike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def strike_params
      params.require(:strike).permit(:onehand, :twohand, :burn, :in, :full)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strikes_helper.rb
module StrikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skogsbrannboll2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/strikes/_form.html.erb
<%= form_for(@strike) do |f| %>
  <% if @strike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@strike.errors.count, "error") %> prohibited this strike from being saved:</h2>

      <ul>
      <% @strike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :onehand %><br>
    <%= f.text_field :onehand %>
  </div>
  <div class="field">
    <%= f.label :twohand %><br>
    <%= f.text_field :twohand %>
  </div>
  <div class="field">
    <%= f.label :burn %><br>
    <%= f.text_field :burn %>
  </div>
  <div class="field">
    <%= f.label :in %><br>
    <%= f.text_field :in %>
  </div>
  <div class="field">
    <%= f.label :full %><br>
    <%= f.text_field :full %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strikes/edit.html.erb
<h1>Editing strike</h1>

<%= render 'form' %>

<%= link_to 'Show', @strike %> |
<%= link_to 'Back', strikes_path %>

app/views/strikes/index.html.erb
<h1>Listing strikes</h1>

<table>
  <thead>
    <tr>
      <th>Onehand</th>
      <th>Twohand</th>
      <th>Burn</th>
      <th>In</th>
      <th>Full</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strikes.each do |strike| %>
      <tr>
        <td><%= strike.onehand %></td>
        <td><%= strike.twohand %></td>
        <td><%= strike.burn %></td>
        <td><%= strike.in %></td>
        <td><%= strike.full %></td>
        <td><%= link_to 'Show', strike %></td>
        <td><%= link_to 'Edit', edit_strike_path(strike) %></td>
        <td><%= link_to 'Destroy', strike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strike', new_strike_path %>

app/views/strikes/new.html.erb
<h1>New strike</h1>

<%= render 'form' %>

<%= link_to 'Back', strikes_path %>

app/views/strikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Onehand:</strong>
  <%= @strike.onehand %>
</p>

<p>
  <strong>Twohand:</strong>
  <%= @strike.twohand %>
</p>

<p>
  <strong>Burn:</strong>
  <%= @strike.burn %>
</p>

<p>
  <strong>In:</strong>
  <%= @strike.in %>
</p>

<p>
  <strong>Full:</strong>
  <%= @strike.full %>
</p>

<%= link_to 'Edit', edit_strike_path(@strike) %> |
<%= link_to 'Back', strikes_path %>